types: use enum class for enums
Using enums allows more precise type checking. The current code in
types.py was already using *Kind classes as if they were enums, which
mypy reported as type errors:

    pygls/types.py:377: error: Incompatible default for argument "severity" (default has type "int", argument has type "DiagnosticSeverity")
    pygls/types.py:663: error: Incompatible default for argument "trace" (default has type "str", argument has type "Optional[Trace]")

WatchKind is handled a bit differently, because valid values can be
combined with |, like the default value 7.